### ISSUE TITLE
Allow user to go back to previous lessons

### ISSUE THREAD

**Issue by aburd** [scootyboots/css-selector-training-platform#3]
## Description

I found myself wanting to go back to previous lessons by clicking on that sweet progress bar

## Wants

- Let me go back by clicking on the circles gosh darnit!

## Nice to have

- When going back to a place, keep the places I've already done "completed" looking. Maybe by maintaining the color?

**Comment by scootyboots** [comment]
Set this up via 3f0c5de80208b9be15d0635cb13830996d98d447 

It's janky AF but it'll do until I implement a global state management solution

**Comment by aburd** [comment]
Sick
