### ISSUE TITLE
Is comma required in the last exercise?

### ISSUE THREAD

**Issue by aburd** [scootyboots/css-selector-training-platform#6]
## Description

The directions just say to select the ones with "new" as their alt text, but I only found elements with alt="new-1" etc.
![Screenshot from 2022-04-01 00-05-29](https://user-images.githubusercontent.com/6701630/161088018-e35c409a-a1c8-4dd0-9283-02d9281a0ab1.png)

Is this correct?

**Comment by scootyboots** [comment]
Yeah, the exercise is supposed to encourage use of [^ or * in the selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) to select elements that are a partial match with the attribute's value.

I'll beef up the hint or prompt to make this more obvious

**Comment by scootyboots** [comment]
Updated the information modal and hint to give better context  b6b3be6672b51b30c21b3c4222a3d670f01dfa68
